#!/bin/bash

# Check if the user provided an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi

IMAGE="$1"

# Send notification to the user
#notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# Set wallpaper
swww img "$IMAGE" --transition-type center
# Generate pywal colors
wal -i "$IMAGE" -n

# Refresh swaync
pkill swaync

# Refresh Spotify
#/home/kylo/.local/bin/pywal-spicetify-smart
pywal-spicetify Dribbblish

pywal-discord

/home/kylo/.local/bin/obsidian-wal

# Use Matugen to generate Material You colors
# matugen image "$IMAGE"

#notify-send "Theme Applied" "Wallpaper and theme updated successfully!"
